stages:
  - build
  - lint

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - client/build

build-library:
  stage: build
  tags:
    - shell
  script:
    - cd client
    - mkdir -p build && cd build
    - cmake ..
    - make

lint-library:
  stage: lint
  tags:
    - shell
  script:
    - cd client/build
    - make cpplint
