[package]
name = "ruads"
version = "0.1.2"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
failure = "0.1.6"
libloading = "0.5.2"
lazy_static = "1.4.0"

[build-dependencies]
cc = "1.0"
